# Generated by Django 6.0.4 on 2026-09-29 19:44

import django.db.models.deletion
from django.db import migrations, models


def crear_unidades_legacy(apps, schema_editor):
    Facultad = apps.get_model("organization", "Facultad")
    Departamento = apps.get_model("organization", "Departamento")
    TipoUnidad = apps.get_model("organization", "TipoUnidadOrganizacional")
    Unidad = apps.get_model("organization", "UnidadOrganizacional")

    universidad_type, _ = TipoUnidad.objects.get_or_create(nombre="Universidad")
    facultad_type, _ = TipoUnidad.objects.get_or_create(nombre="Facultad")
    departamento_type, _ = TipoUnidad.objects.get_or_create(nombre="Departamento")
    universidad, _ = Unidad.objects.get_or_create(
        nombre="UASD", tipo=universidad_type, unidad_padre=None
    )

    facultades = {}
    for facultad in Facultad.objects.order_by("pk"):
        unidad, _ = Unidad.objects.get_or_create(
            nombre=facultad.nombre,
            tipo=facultad_type,
            unidad_padre=universidad,
            defaults={"descripcion": facultad.descripcion, "activa": facultad.activo},
        )
        facultades[facultad.pk] = unidad

    for departamento in Departamento.objects.select_related("facultad").order_by("pk"):
        Unidad.objects.get_or_create(
            departamento_legacy_id=departamento.pk,
            defaults={
                "nombre": departamento.nombre,
                "descripcion": departamento.descripcion,
                "tipo": departamento_type,
                "unidad_padre": facultades[departamento.facultad_id],
                "activa": departamento.activo,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento_legacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_organizacionales', to='organization.departamento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='organization.tipounidadorganizacional')),
                ('unidad_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunidades', to='organization.unidadorganizacional')),
            ],
        ),
        migrations.RunPython(crear_unidades_legacy, migrations.RunPython.noop),
    ]
