# Generated by Django 6.0.4 on 2026-09-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_tipounidadorganizacional_unidadorganizacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='unidad_organizacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='organization.unidadorganizacional'),
        ),
    ]
