# Generated by Django 6.0.4 on 2026-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0006_periodo_periodo_fecha_fin_posterior_inicio_and_more'),
        ('organization', '0005_remove_perfilusuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='periodos_autorizados',
            field=models.ManyToManyField(blank=True, related_name='perfiles_evaluador_externo', to='evaluation.periodo'),
        ),
    ]
