# Generated by Django 6.0.4 on 2026-09-30 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0006_periodo_periodo_fecha_fin_posterior_inicio_and_more'),
        ('organization', '0006_perfilusuario_periodos_autorizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def migrate_period_authorizations(apps, schema_editor):
        PerfilUsuario = apps.get_model('organization', 'PerfilUsuario')
        AmbitoEvaluacion = apps.get_model('organization', 'AmbitoEvaluacion')
        through_model = PerfilUsuario.periodos_autorizados.through
        for perfil in PerfilUsuario.objects.exclude(unidad_organizacional_id__isnull=True):
            period_ids = through_model.objects.filter(perfilusuario_id=perfil.pk).values_list(
                'periodo_id', flat=True
            )
            AmbitoEvaluacion.objects.bulk_create(
                [
                    AmbitoEvaluacion(
                        usuario_id=perfil.usuario_id,
                        unidad_organizacional_id=perfil.unidad_organizacional_id,
                        periodo_id=periodo_id,
                        activo=True,
                    )
                    for periodo_id in period_ids
                ],
                ignore_conflicts=True,
            )

    operations = [
        migrations.CreateModel(
            name='AmbitoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambitos_evaluacion', to='evaluation.periodo')),
                ('unidad_organizacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambitos_evaluacion', to='organization.unidadorganizacional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambitos_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username', 'periodo__fecha_inicio', 'unidad_organizacional__nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'unidad_organizacional', 'periodo'), name='ambito_evaluacion_usuario_unidad_periodo_unico')],
            },
        ),
        migrations.RunPython(migrate_period_authorizations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='periodos_autorizados',
        ),
    ]
