apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: evaluacion-quinquenal
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-me-in-production"
  DB_NAME: "evaluacion_quinquenal"
  DB_USER: "evaluacion_user"
  DB_PASSWORD: "evaluacion_pass"
  POSTGRES_DB: "evaluacion_quinquenal"
  POSTGRES_USER: "evaluacion_user"
  POSTGRES_PASSWORD: "evaluacion_pass"
