# Generated by Django 6.0.3 on 2026-06-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VersionEvidencia',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('version', models.IntegerField(default=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='evidence.evidencia')),
            ],
        ),
    ]
