# Generated by Django 6.0.3 on 2026-06-30 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='evaluation.asignacion'),
        ),
    ]
