# Generated by Django 6.0.5 on 2026-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_evidencia_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
