# Generated by Django 6.0.5 on 2026-07-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
