export const PERMISSION_LABELS: Record<string, string> = {
  'auth.add_user': 'Añadir usuario',
  'auth.change_user': 'Editar usuario',
  'auth.delete_user': 'Eliminar usuario',
  'auth.view_user': 'Ver usuario',
  'auth.add_group': 'Añadir rol',
  'auth.change_group': 'Editar rol',
  'auth.delete_group': 'Eliminar rol',
  'auth.view_group': 'Ver rol',
  'auth.add_permission': 'Añadir permiso',
  'auth.change_permission': 'Editar permiso',
  'auth.delete_permission': 'Eliminar permiso',
  'auth.view_permission': 'Ver permiso',

  'accounts.add_usuario': 'Añadir usuario',
  'accounts.change_usuario': 'Editar usuario',
  'accounts.delete_usuario': 'Eliminar usuario',
  'accounts.view_usuario': 'Ver usuario',

  'evaluation.view_periodo': 'Ver período',
  'evaluation.add_periodo': 'Añadir período',
  'evaluation.change_periodo': 'Editar período',
  'evaluation.delete_periodo': 'Eliminar período',
  'evaluation.view_criterio': 'Ver criterio',
  'evaluation.add_criterio': 'Añadir criterio',
  'evaluation.change_criterio': 'Editar criterio',
  'evaluation.delete_criterio': 'Eliminar criterio',
  'evaluation.view_indicador': 'Ver indicador',
  'evaluation.add_indicador': 'Añadir indicador',
  'evaluation.change_indicador': 'Editar indicador',
  'evaluation.delete_indicador': 'Eliminar indicador',
  'evaluation.view_asignacion': 'Ver asignación',
  'evaluation.add_asignacion': 'Añadir asignación',
  'evaluation.change_asignacion': 'Editar asignación',
  'evaluation.delete_asignacion': 'Eliminar asignación',
  'evaluation.view_historialestado': 'Ver historial de estado',
  'evaluation.add_historialestado': 'Añadir historial de estado',
  'evaluation.change_historialestado': 'Editar historial de estado',
  'evaluation.delete_historialestado': 'Eliminar historial de estado',

  'evidence.view_evidencia': 'Ver evidencia',
  'evidence.add_evidencia': 'Añadir evidencia',
  'evidence.change_evidencia': 'Editar evidencia',
  'evidence.delete_evidencia': 'Eliminar evidencia',
  'evidence.view_versionevidencia': 'Ver versión de evidencia',
  'evidence.add_versionevidencia': 'Añadir versión de evidencia',
  'evidence.change_versionevidencia': 'Editar versión de evidencia',
  'evidence.delete_versionevidencia': 'Eliminar versión de evidencia',
  'evidence.view_observacion': 'Ver observación',
  'evidence.add_observacion': 'Añadir observación',
  'evidence.change_observacion': 'Editar observación',
  'evidence.delete_observacion': 'Eliminar observación',

  'evidencias.view_evidencia': 'Ver evidencia (antigua)',
  'evidencias.add_evidencia': 'Añadir evidencia (antigua)',
  'evidencias.change_evidencia': 'Editar evidencia (antigua)',
  'evidencias.delete_evidencia': 'Eliminar evidencia (antigua)',

  'organization.view_facultad': 'Ver facultad',
  'organization.add_facultad': 'Añadir facultad',
  'organization.change_facultad': 'Editar facultad',
  'organization.delete_facultad': 'Eliminar facultad',
  'organization.view_departamento': 'Ver departamento',
  'organization.add_departamento': 'Añadir departamento',
  'organization.change_departamento': 'Editar departamento',
  'organization.delete_departamento': 'Eliminar departamento',
  'organization.view_perfilusuario': 'Ver perfil de usuario',
  'organization.add_perfilusuario': 'Añadir perfil de usuario',
  'organization.change_perfilusuario': 'Editar perfil de usuario',
  'organization.delete_perfilusuario': 'Eliminar perfil de usuario',

  'notificaciones.view_notificacion': 'Ver notificación',
  'notificaciones.add_notificacion': 'Añadir notificación',
  'notificaciones.change_notificacion': 'Editar notificación',
  'notificaciones.delete_notificacion': 'Eliminar notificación',

  'auditoria.view_auditoria': 'Ver auditoría',
  'auditoria.add_auditoria': 'Añadir auditoría',
  'auditoria.change_auditoria': 'Editar auditoría',
  'auditoria.delete_auditoria': 'Eliminar auditoría',

  'dashboard.view_resumen': 'Ver resumen del dashboard',
  'dashboard.view_avance': 'Ver avance del dashboard',
};